# Generated by Django 4.2.10 on 2024-03-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0002_alter_userprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
    ]
