# Generated by Django 4.2.10 on 2024-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0003_remove_userprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='guide',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='joined_in_farming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='joined_in_gardening',
            field=models.BooleanField(default=False),
        ),
    ]
